### ISSUE TITLE
Peer-to-peer Review

### ISSUE THREAD

**Issue by bhskr44** [bhskr44/MyPortfolio#5]
Peer-to-peer Review Done by microverse week 2 day 4

**Comment by codedbystuart** [comment]
Awesome job @bhskr44.
Just a few comments about your code. I would advice you provide `alt` attribute to your `img` tags 
so that you can always give a nice message about the image in that particular position

**Comment by bhskr44** [comment]
> Awesome job @bhskr44. Just a few comments about your code. I would advice you provide `alt` attribute to your `img` tags so that you can always give a nice message about the image in that particular position

@codedbystuart Thank you for addressing the issue. It helped a lot.

**Comment by AHP15** [comment]
Hi @bhskr44 great job, comments are great and the code structure is nice
Like @codedbystuart said I suggest adding an alt attribute to the image tags.
And in the review.css file 
![review2](https://user-images.githubusercontent.com/95412943/192966905-33f34c23-4a4a-4c34-8cf3-7fecf12eb6e0.PNG)
Please add "display: block" to apply the margin (img tag has an inline display)

**Comment by MosDevx** [comment]
<div class="my-work">
          <img src="image/works/Snapshoot Portfolio3.svg" />
        <h2>Tonic</h2>

Kindly remove spaces between the src

**Comment by MosDevx** [comment]
code is clean and well structured. great job :+1:
